//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediant
    {
        public int IngId { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string Measurement { get; set; }
        public bool DeleteIng { get; set; }
        public int RecipeId { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
